### ISSUE TITLE
Lost access to PPM snapshots from ~2019

### ISSUE THREAD

**Issue by pawelru** [r-lib/pkgcache#115]
ATM I have the following:

```
r$> pkgcache::ppm_snapshots() |> head()
# A data frame: 6 × 2
  date                   id
* <dttm>              <int>
1 2020-03-09 00:00:00     0
2 2020-03-12 00:00:00     0
3 2020-03-16 00:00:00     0
4 2020-03-19 00:00:00     0
5 2020-03-23 00:00:00     0
6 2020-03-26 00:00:00     0
```

In [the other issue I reported some time ago](https://github.com/r-lib/pkgcache/issues/110) I had access to `2019-07-11`.
In the [PPM](https://packagemanager.posit.co/cran/) itself I have access to `2017-10-10`.

**Comment by gaborcsardi** [comment]
This is because of a PPM API change, it returns at most 1000 transactions now at `https://packagemanager.posit.co/__api__/sources/1/transactions`, even if I set a higher limit.

**Comment by pawelru** [comment]
How about a while loop iterating on the `_page` parameter? I can see that there is something like https://packagemanager.posit.co/__api__/sources/1/transactions?_limit=1000&_page=2
