### ISSUE TITLE
Release first version to CRAN

### ISSUE THREAD

**Issue by gaborcsardi** [r-lib/pkgcache#2]
* [x] `devtools::check_win_devel()`
* [x] `rhub::check_for_cran()`
* [x] ~~`revdepcheck::revdep_check(num_workers = 4)`~~
* [x] [Polish NEWS](http://style.tidyverse.org/news.html#before-release)
* [x] ~~If new failures, update `email.yml` then `revdepcheck::revdep_email_maintainers()`~~
* [x] Bump version (in DESCRIPTION and NEWS)
* [x] ~~`devtools::check_win_devel()` (again!)~~
* [x] `devtools::submit_cran()`
* [x] ~~`pkgdown::build_site()`~~
* [ ] Approve email
* [ ] Tag release
* [ ] Bump dev version
* [x] ~~Write blog post~~
* [x] ~~Tweet~~

**Comment by gaborcsardi** [comment]
@jimhester @hadley Pls take a look at the API.

**Comment by hadley** [comment]
Is this used by pkgman?

**Comment by gaborcsardi** [comment]
Yes, of course. It is out of pkgdepends. (Which still needs an update to
use pkgcache.)

**Comment by gaborcsardi** [comment]
NEed to fix #6 and  #7 first....

**Comment by gaborcsardi** [comment]
Start this over....
