### ISSUE TITLE
Unable to update metadata cache when using enterprise CRAN mirror

### ISSUE THREAD

**Issue by timmsm** [r-lib/pkgcache#21]
[Artifactory's](https://jfrog.com/artifactory/) enterprise CRAN mirror currently has a [bug](https://www.jfrog.com/jira/si/jira.issueviews:issue-html/RTFACT-17392/RTFACT-17392.html) where the mirror has a `PACKAGES` file but not `PACKAGES.gz`. Would it be possible to add a HEAD request to `cmc__get_cache_files` to check if `PACKAGES.gz` exists in the specified CRAN repo and, if not, fall back to `PACKAGES` (which should exist in every CRAN repo)?

This affects both `pkgcache::meta_cache_list()` and `pkgcache::cranlike_metadata_cache$new()$list()`.

**Comment by timmsm** [comment]
You're definitely right that this is kind of a niche issue. Outside of my current context, I have no idea how many Artifactory users there are or how many users in general are stuck using some kind of wonky CRAN-like enterprise mirror.

However, if it's just a quick fix (maybe either a defensive HEAD request or catching the 404 and trying again) it would be greatly appreciated as it would help sidestep this family of errors and would remove one of the blockers for using `pak` (which I'm super excited about!) in our dev environment.

I'd also be more than happy to submit a PR for you to review!

**Comment by gaborcsardi** [comment]
Sure, a PR sounds great!

**Comment by gaborcsardi** [comment]
Closed by #27.
