### ISSUE TITLE
Suggestion: export http async code as new package

### ISSUE THREAD

**Issue by Hong-Revo** [r-lib/pkgcache#40]
Functions like `http_get`, `http_put` etc would be incredibly useful in their own right. Perhaps it could be part of httr2 if/when that gets started?

**Comment by gaborcsardi** [comment]
Potentially, yes. You can already do async HTTP with the `multi_*` functions of the curl package, although it is a bit low level. But anyway, this is not in the plans currently, so I'll close this issue now.
