### ISSUE TITLE
Next cran release?

### ISSUE THREAD

**Issue by officialpatterson** [r-lib/pkgcache#58]
Hi,

Looking to take advantage of the repo_resolve function from inside a docker container but devtools_install_github times out. AFAIK that is a known issue, but I'd prefer to use a releases version of this package anyways - is there a release schedule for this package so that I know when it will be available?

Cheers.

Andy P.

**Comment by gaborcsardi** [comment]
There is no schedule, I would think a couple of weeks.

FWIW, this is supported in the dev version of pak already, you can install it with 
```r
install.packages("pak", repos = "https://r-lib.github.io/p/pak/dev/")
pak::repo_resolve("RSPM@2020-01-30")
```
This works for any x86_64 Linux, for R 3.3 and later. See https://github.com/r-lib/pak#installation.

**Comment by gaborcsardi** [comment]
Just happened.
